import Head from "next/head";
import { Card, Heading, Button } from "@chakra-ui/react";
import { useEffect } from "react";
import { axiosInstance } from "../lib/axios";
import { useState } from "react";

// cakra ui for CSS
// axios for api calls
// yup for validation
// formik for forms validation
// react-query for manage api calls (cachin and more state dll)

export default function Home() {
  const [products, setProducts] = useState([]);

  // akses database api
  const fetchProduct = async () => {
    try {
      // Penerapan konsep DRY (do not repeat yourself)
      const productResponse = await axiosInstance.get("/product");

      setProducts(productResponse.data);
    } catch (error) {
      console.log(error);
    }
  };

  // menampilakan database ke website
  const renderProducts = () => {
    return products.map((product) => {
      return (
        <Card key={product.id.toString()}>
          <h1>{product.title}</h1>
          <img src={product.image} alt={product.title} />
          <p>{product.price}</p>
          <p>{product.description}</p>
        </Card>
      );
    });
  };

  useEffect(() => {
    fetchProduct();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading>Hello world!</Heading>
        <Card>
          
        <Button colorScheme='blue'>Button</Button>
        </Card>
      </main>
    </>
  );
}
